### ISSUE TITLE
PHP Notice:  Undefined property: stdClass::$group in /classes/User.php on line 97

### ISSUE THREAD

**Issue by attilaantal** [attilaantal/PHP-OOP-Login-Register-System#3]
Code references the "group" variable which is not available.

**Comment by attilaantal** [comment]
For some reason, the group field was not inserted into the groups table, and the PHP logic was referring to it. 
Creating the "**group**" column manually will resolve this issue.

**Comment by TrevorThebe** [comment]
Hi man what goes into the group after creating it? I have created it but not working still. Thanks for the awsome tut

**Comment by TrevorThebe** [comment]
ah it worked thanks I'm good now thanks
